FROM debian:stretch

RUN apt-get clean \
    && apt-get autoclean \
    && apt-get install libc6 \
    && apt-get update

RUN apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev \
    libnss3-dev libssl-dev libreadline-dev libffi-dev wget -y \
    && wget https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tar.xz \
    && tar -xf Python-3.8.1.tar.xz \
    && cd Python-3.8.1 \
    && ./configure --enable-optimizations \
    && make altinstall

RUN cd /var \
    && touch flag \
    && chmod 777 flag
#
COPY . ivan/
CMD ["python3.8", "ivan/hw.py"]

